/**
 * scripts/gen_zeros.js
 *
 * Generates real Poseidon zero values using circomlibjs.
 * Run AFTER npm install:
 *
 *   node scripts/gen_zeros.js
 *
 * Copy the output into:
 *   1. contracts/src/lib.rs  → ZEROS constant
 *   2. lib/merkle/tree.ts    → initZeros() to cross-check
 */

const { buildPoseidon } = require('circomlibjs')

async function main() {
  console.log('Building Poseidon hasher...')
  const poseidon = await buildPoseidon()

  function hash(...inputs) {
    const mapped = inputs.map(x => BigInt(x))
    const result = poseidon(mapped)
    return poseidon.F.toObject(result)
  }

  const DEPTH = 20
  const zeros = []
  zeros[0] = hash(0n)
  for (let i = 1; i <= DEPTH; i++) {
    zeros[i] = hash(zeros[i - 1], zeros[i - 1])
  }

  console.log('\n✅ Paste this into contracts/src/lib.rs (replace the ZEROS constant):\n')
  console.log('const ZEROS: [&str; 21] = [')
  for (let i = 0; i <= DEPTH; i++) {
    const comma = i < DEPTH ? ',' : ''
    console.log(`    "${zeros[i]}"${comma}`)
  }
  console.log('];')

  console.log('\n✅ Paste this into lib/merkle/tree.ts (replace initZeros body):\n')
  console.log('// Auto-generated by scripts/gen_zeros.js')
  console.log('const POSEIDON_ZEROS: bigint[] = [')
  for (let i = 0; i <= DEPTH; i++) {
    const comma = i < DEPTH ? ',' : ''
    console.log(`  ${zeros[i]}n${comma}`)
  }
  console.log(']')

  console.log('\nVerification:')
  console.log('  zeros[0]  =', zeros[0].toString())
  console.log('  zeros[1]  =', zeros[1].toString())
  console.log('  zeros[20] =', zeros[20].toString())
}

main().catch(err => { console.error(err); process.exit(1) })
